import { Company, DataProvider } from "./types";

export const companies: Company[] = [
  {
    id: "vanta",
    name: "Vanta",
    url: "https://www.vanta.com",
    description: "Compliance automation for fast-growing SaaS teams.",
    industry: "Compliance Automation",
    employeeCount: 420,
    fundingStage: "Series C",
    fundingAmount: "$200M total",
    arrEstimate: "$50M-$100M",
    headquarters: "San Francisco, CA",
    region: "NAM",
    products: ["SOC 2 automation", "ISO 27001", "Vendor risk management", "Trust center"],
    demoPageUrl: "https://www.vanta.com/demo",
    techStack: ["AWS", "Kubernetes", "Segment", "Salesforce", "HubSpot"],
    buyerPersonas: ["Head of Security", "Compliance Manager", "RevOps"],
    hiringSignals: ["Hiring SDRs", "Hiring GRC analysts", "Scaling RevOps"],
    painSignals: [
      "Prospects require compliance proof before demos",
      "Manual evidence collection slows sales cycles",
      "Multiple regional compliance requirements",
    ],
  },
  {
    id: "deel",
    name: "Deel",
    url: "https://www.deel.com",
    description: "Global payroll and HR for distributed teams.",
    industry: "Global HR & Payroll",
    employeeCount: 480,
    fundingStage: "Series C",
    fundingAmount: "$630M total",
    arrEstimate: "$200M-$400M",
    headquarters: "San Francisco, CA",
    region: "NAM",
    products: ["Global payroll", "Employer of record", "Contractor management", "HRIS"],
    demoPageUrl: "https://www.deel.com/request-a-demo",
    techStack: ["AWS", "Salesforce", "Marketo", "Segment", "Datadog"],
    buyerPersonas: ["VP People", "Head of Global HR", "CFO"],
    hiringSignals: ["Hiring SDRs", "Hiring demand gen", "Hiring customer ops"],
    painSignals: [
      "High inbound demo volume across regions",
      "Complex routing by country and entity type",
      "Speed-to-lead impacts conversion in competitive HR market",
    ],
  },
  {
    id: "lattice",
    name: "Lattice",
    url: "https://lattice.com",
    description: "People management platform for performance and engagement.",
    industry: "People Management",
    employeeCount: 350,
    fundingStage: "Series C",
    fundingAmount: "$330M total",
    arrEstimate: "$100M-$200M",
    headquarters: "San Francisco, CA",
    region: "NAM",
    products: ["Performance reviews", "Engagement surveys", "Compensation", "HRIS"],
    demoPageUrl: "https://lattice.com/demo",
    techStack: ["AWS", "Salesforce", "HubSpot", "Gainsight", "Snowflake"],
    buyerPersonas: ["VP People", "Head of HR", "People Ops"],
    hiringSignals: ["Hiring SDRs", "Hiring RevOps", "Scaling customer success"],
    painSignals: [
      "Multiple product lines require segmented routing",
      "High demo request volume from mid-market",
      "Complex enterprise approval workflows",
    ],
  },
  {
    id: "ramp",
    name: "Ramp",
    url: "https://ramp.com",
    description: "Corporate spend management and finance automation.",
    industry: "Spend Management",
    employeeCount: 500,
    fundingStage: "Series D+",
    fundingAmount: "$700M total",
    arrEstimate: "$200M-$400M",
    headquarters: "New York, NY",
    region: "NAM",
    products: ["Corporate cards", "Expense management", "Bill pay", "Procurement"],
    demoPageUrl: "https://ramp.com/demo",
    techStack: ["AWS", "Snowflake", "Salesforce", "Segment", "Looker"],
    buyerPersonas: ["CFO", "VP Finance", "Controller"],
    hiringSignals: ["Hiring SDRs", "Hiring enterprise AEs", "Scaling revenue ops"],
    painSignals: [
      "High-intent inbound from paid finance keywords",
      "Routing by spend size and vertical",
      "Fast response time critical for conversion",
    ],
  },
  {
    id: "jasper",
    name: "Jasper",
    url: "https://www.jasper.ai",
    description: "AI content platform for marketing teams.",
    industry: "AI Content Platform",
    employeeCount: 220,
    fundingStage: "Series B",
    fundingAmount: "$130M total",
    arrEstimate: "$50M-$100M",
    headquarters: "Austin, TX",
    region: "NAM",
    products: ["Brand voice", "Content workflows", "AI writing", "Campaign briefs"],
    demoPageUrl: "https://www.jasper.ai/demo",
    techStack: ["AWS", "HubSpot", "Salesforce", "Segment", "Amplitude"],
    buyerPersonas: ["VP Marketing", "Demand Gen", "Content Ops"],
    hiringSignals: ["Hiring SDRs", "Hiring lifecycle marketers", "Scaling RevOps"],
    painSignals: [
      "Marketing-led inbound needs rapid qualification",
      "Multiple ICP segments across verticals",
      "Demo conversion impacted by routing delays",
    ],
  },
  {
    id: "gong",
    name: "Gong",
    url: "https://www.gong.io",
    description: "Revenue intelligence platform for sales teams.",
    industry: "Revenue Intelligence",
    employeeCount: 480,
    fundingStage: "Series D+",
    fundingAmount: "$580M total",
    arrEstimate: "$200M-$400M",
    headquarters: "San Francisco, CA",
    region: "NAM",
    products: ["Conversation intelligence", "Forecasting", "Deal insights", "Sales coaching"],
    demoPageUrl: "https://www.gong.io/demo",
    techStack: ["AWS", "Salesforce", "Marketo", "Snowflake", "Segment"],
    buyerPersonas: ["VP Sales", "Revenue Ops", "CRO"],
    hiringSignals: ["Hiring SDRs", "Hiring RevOps", "Expanding enterprise sales"],
    painSignals: [
      "High demo volume from paid and partner channels",
      "Complex routing by region and segment",
      "Speed-to-lead affects enterprise conversion",
    ],
  },
  {
    id: "notion",
    name: "Notion",
    url: "https://www.notion.so",
    description: "Connected workspace for docs, projects, and knowledge.",
    industry: "Productivity Software",
    employeeCount: 450,
    fundingStage: "Series D+",
    fundingAmount: "$340M total",
    arrEstimate: "$200M-$400M",
    headquarters: "San Francisco, CA",
    region: "NAM",
    products: ["Docs", "Projects", "Knowledge base", "AI workspace"],
    demoPageUrl: "https://www.notion.so/sales",
    techStack: ["AWS", "Segment", "Snowflake", "Salesforce", "Amplitude"],
    buyerPersonas: ["Head of IT", "VP Operations", "RevOps"],
    hiringSignals: ["Hiring SDRs", "Hiring enterprise AEs", "Scaling customer marketing"],
    painSignals: [
      "Enterprise inbound requires fast routing",
      "Multiple product lines create routing complexity",
      "Demos needed for large workspace rollouts",
    ],
  },
  {
    id: "linear",
    name: "Linear",
    url: "https://linear.app",
    description: "Issue tracking and project management for product teams.",
    industry: "Project Management",
    employeeCount: 180,
    fundingStage: "Series B",
    fundingAmount: "$90M total",
    arrEstimate: "$30M-$60M",
    headquarters: "San Francisco, CA",
    region: "NAM",
    products: ["Issue tracking", "Roadmaps", "Cycles", "Insights"],
    demoPageUrl: "https://linear.app/demo",
    techStack: ["AWS", "Segment", "HubSpot", "Snowflake", "Mixpanel"],
    buyerPersonas: ["VP Product", "Head of Engineering", "Product Ops"],
    hiringSignals: ["Hiring SDRs", "Hiring enterprise AEs", "Scaling RevOps"],
    painSignals: [
      "Enterprise deals require tailored demos",
      "Routing by team size and product tier",
      "Response time affects competitive win rates",
    ],
  },
  {
    id: "loom",
    name: "Loom",
    url: "https://www.loom.com",
    description: "Async video messaging for modern teams.",
    industry: "Collaboration Software",
    employeeCount: 320,
    fundingStage: "Series C",
    fundingAmount: "$200M total",
    arrEstimate: "$50M-$100M",
    headquarters: "San Francisco, CA",
    region: "NAM",
    products: ["Video messaging", "Screen recording", "Team libraries", "AI summaries"],
    demoPageUrl: "https://www.loom.com/demo",
    techStack: ["AWS", "Segment", "HubSpot", "Amplitude", "Salesforce"],
    buyerPersonas: ["VP Operations", "Head of IT", "RevOps"],
    hiringSignals: ["Hiring SDRs", "Hiring growth marketers", "Scaling enterprise sales"],
    painSignals: [
      "High inbound from self-serve users upgrading",
      "Routing across SMB and enterprise segments",
      "Speed-to-lead impacts conversion",
    ],
  },
  {
    id: "drata",
    name: "Drata",
    url: "https://drata.com",
    description: "Security compliance automation and continuous monitoring.",
    industry: "Compliance Automation",
    employeeCount: 300,
    fundingStage: "Series C",
    fundingAmount: "$320M total",
    arrEstimate: "$80M-$150M",
    headquarters: "San Diego, CA",
    region: "NAM",
    products: ["SOC 2", "ISO 27001", "Continuous monitoring", "Trust center"],
    demoPageUrl: "https://drata.com/demo",
    techStack: ["AWS", "Salesforce", "HubSpot", "Segment", "Gong"],
    buyerPersonas: ["CISO", "Security Lead", "Compliance Manager"],
    hiringSignals: ["Hiring SDRs", "Hiring partner managers", "Scaling customer success"],
    painSignals: [
      "Compliance proof gating enterprise demos",
      "Routing by industry and audit type",
      "Manual qualification slows conversion",
    ],
  },
  {
    id: "koala",
    name: "Koala",
    url: "https://www.koala.ai",
    description: "Intent data and website personalization for B2B marketing.",
    industry: "Intent Data",
    employeeCount: 90,
    fundingStage: "Series A",
    fundingAmount: "$35M total",
    arrEstimate: "$10M-$25M",
    headquarters: "San Francisco, CA",
    region: "NAM",
    products: ["Website personalization", "Account intent", "Sales alerts"],
    demoPageUrl: "https://www.koala.ai/demo",
    techStack: ["AWS", "HubSpot", "Segment", "Clearbit", "Amplitude"],
    buyerPersonas: ["VP Marketing", "Demand Gen", "RevOps"],
    hiringSignals: ["Hiring SDRs", "Hiring growth marketers", "Hiring RevOps"],
    painSignals: [
      "High inbound from paid channels needs fast routing",
      "Multiple ICP segments for personalization",
      "Manual lead qualification slows pipeline",
    ],
  },
  {
    id: "clay",
    name: "Clay",
    url: "https://www.clay.com",
    description: "Data enrichment and GTM workflows for revenue teams.",
    industry: "Data Enrichment",
    employeeCount: 160,
    fundingStage: "Series B",
    fundingAmount: "$65M total",
    arrEstimate: "$20M-$40M",
    headquarters: "New York, NY",
    region: "NAM",
    products: ["Enrichment workflows", "Waterfall data", "GTM automation"],
    demoPageUrl: "https://www.clay.com/demo",
    techStack: ["AWS", "Segment", "HubSpot", "Snowflake", "Mixpanel"],
    buyerPersonas: ["RevOps", "Growth", "Sales Ops"],
    hiringSignals: ["Hiring SDRs", "Hiring customer success", "Scaling RevOps"],
    painSignals: [
      "Inbound from multiple channels needs smart routing",
      "Complex lead scoring and qualification",
      "Speed-to-lead critical for pipeline conversion",
    ],
  },
  {
    id: "warmly",
    name: "Warmly",
    url: "https://www.warmly.ai",
    description: "Intent signals and pipeline generation for B2B teams.",
    industry: "Intent Signals",
    employeeCount: 70,
    fundingStage: "Series A",
    fundingAmount: "$30M total",
    arrEstimate: "$8M-$15M",
    headquarters: "San Francisco, CA",
    region: "NAM",
    products: ["Intent detection", "Website identification", "Prospect alerts"],
    demoPageUrl: "https://www.warmly.ai/demo",
    techStack: ["AWS", "HubSpot", "Segment", "Clearbit", "Salesforce"],
    buyerPersonas: ["VP Sales", "RevOps", "Demand Gen"],
    hiringSignals: ["Hiring SDRs", "Hiring demand gen", "Scaling RevOps"],
    painSignals: [
      "High inbound web traffic requires instant routing",
      "Multiple buyer personas to qualify",
      "Manual handoffs slow conversion",
    ],
  },
  {
    id: "pylon",
    name: "Pylon",
    url: "https://www.usepylon.com",
    description: "B2B customer support platform built for high-touch teams.",
    industry: "Customer Support",
    employeeCount: 95,
    fundingStage: "Series A",
    fundingAmount: "$30M total",
    arrEstimate: "$10M-$20M",
    headquarters: "San Francisco, CA",
    region: "NAM",
    products: ["Shared inbox", "Customer portal", "Support automation"],
    demoPageUrl: "https://www.usepylon.com/demo",
    techStack: ["AWS", "Segment", "HubSpot", "Intercom", "Snowflake"],
    buyerPersonas: ["Head of Support", "VP Customer Success", "RevOps"],
    hiringSignals: ["Hiring SDRs", "Hiring CSMs", "Scaling support ops"],
    painSignals: [
      "Support-led inbound needs fast qualification",
      "Routing by segment and SLA tier",
      "Demos required for enterprise evaluation",
    ],
  },
  {
    id: "correlated",
    name: "Correlated",
    url: "https://www.correlated.com",
    description: "Product-led sales signals and scoring platform.",
    industry: "Product-Led Sales",
    employeeCount: 80,
    fundingStage: "Series A",
    fundingAmount: "$20M total",
    arrEstimate: "$5M-$12M",
    headquarters: "New York, NY",
    region: "NAM",
    products: ["Product signals", "Account scoring", "Playbooks"],
    demoPageUrl: "https://www.correlated.com/demo",
    techStack: ["AWS", "Segment", "HubSpot", "Snowflake", "Amplitude"],
    buyerPersonas: ["RevOps", "VP Sales", "Product Ops"],
    hiringSignals: ["Hiring SDRs", "Hiring product marketers", "Scaling RevOps"],
    painSignals: [
      "Multiple product signals need routing",
      "Inbound qualification requires fast triage",
      "High-velocity PLG upgrades",
    ],
  },
  {
    id: "dock",
    name: "Dock",
    url: "https://www.dock.us",
    description: "Deal rooms and buyer enablement workspace.",
    industry: "Buyer Enablement",
    employeeCount: 120,
    fundingStage: "Series B",
    fundingAmount: "$60M total",
    arrEstimate: "$15M-$30M",
    headquarters: "New York, NY",
    region: "NAM",
    products: ["Deal rooms", "Mutual action plans", "Buyer content"],
    demoPageUrl: "https://www.dock.us/demo",
    techStack: ["AWS", "HubSpot", "Salesforce", "Segment", "Mixpanel"],
    buyerPersonas: ["VP Sales", "RevOps", "Sales Enablement"],
    hiringSignals: ["Hiring SDRs", "Hiring enablement", "Scaling RevOps"],
    painSignals: [
      "High demo dependency for enterprise deals",
      "Routing by segment and use case",
      "Speed-to-lead critical in competitive deals",
    ],
  },
  {
    id: "tourial",
    name: "Tourial",
    url: "https://www.tourial.com",
    description: "Interactive product tours for sales and marketing.",
    industry: "Interactive Demos",
    employeeCount: 60,
    fundingStage: "Series A",
    fundingAmount: "$20M total",
    arrEstimate: "$5M-$10M",
    headquarters: "Seattle, WA",
    region: "NAM",
    products: ["Interactive tours", "Sales demos", "Product walkthroughs"],
    demoPageUrl: "https://www.tourial.com/demo",
    techStack: ["AWS", "HubSpot", "Segment", "Intercom", "Mixpanel"],
    buyerPersonas: ["VP Marketing", "Sales Enablement", "Product Marketing"],
    hiringSignals: ["Hiring SDRs", "Hiring demand gen", "Scaling sales team"],
    painSignals: [
      "Inbound demo requests need rapid routing",
      "Multiple product lines require tailored demos",
      "Manual qualification slows sales velocity",
    ],
  },
  {
    id: "navattic",
    name: "Navattic",
    url: "https://www.navattic.com",
    description: "Interactive product demos for revenue teams.",
    industry: "Interactive Demos",
    employeeCount: 110,
    fundingStage: "Series A",
    fundingAmount: "$30M total",
    arrEstimate: "$10M-$20M",
    headquarters: "New York, NY",
    region: "NAM",
    products: ["Interactive demos", "Demo analytics", "Showcase templates"],
    demoPageUrl: "https://www.navattic.com/demo",
    techStack: ["AWS", "HubSpot", "Segment", "Salesforce", "Amplitude"],
    buyerPersonas: ["VP Marketing", "Sales Enablement", "RevOps"],
    hiringSignals: ["Hiring SDRs", "Hiring growth marketers", "Scaling RevOps"],
    painSignals: [
      "High inbound from demo content",
      "Routing by persona and use case",
      "Speed-to-lead impacts demo-to-meeting rates",
    ],
  },
  {
    id: "storylane",
    name: "Storylane",
    url: "https://www.storylane.io",
    description: "Demo automation platform for modern sales teams.",
    industry: "Demo Automation",
    employeeCount: 140,
    fundingStage: "Series A",
    fundingAmount: "$20M total",
    arrEstimate: "$10M-$20M",
    headquarters: "San Francisco, CA",
    region: "NAM",
    products: ["Demo builder", "Interactive walkthroughs", "Personalized demos"],
    demoPageUrl: "https://www.storylane.io/demo",
    techStack: ["AWS", "HubSpot", "Segment", "Mixpanel", "Salesforce"],
    buyerPersonas: ["Sales Enablement", "VP Sales", "Product Marketing"],
    hiringSignals: ["Hiring SDRs", "Hiring RevOps", "Scaling enterprise sales"],
    painSignals: [
      "Demo-first sales motion requires routing",
      "Multiple personas need tailored demos",
      "Fast follow-up drives conversion",
    ],
  },
  {
    id: "chili-piper",
    name: "Chili Piper",
    url: "https://www.chilipiper.com",
    description: "Meeting scheduling and lead routing for revenue teams.",
    industry: "Scheduling & Routing",
    employeeCount: 180,
    fundingStage: "Series B",
    fundingAmount: "$54M total",
    arrEstimate: "$30M-$60M",
    headquarters: "Brooklyn, NY",
    region: "NAM",
    products: ["Instant Booker", "Demand conversion", "Lead routing"],
    demoPageUrl: "https://www.chilipiper.com/demo",
    techStack: ["AWS", "Salesforce", "HubSpot", "Segment", "Marketo"],
    buyerPersonas: ["RevOps", "VP Sales", "Demand Gen"],
    hiringSignals: ["Hiring SDRs", "Hiring RevOps", "Scaling customer marketing"],
    painSignals: [
      "High inbound requires instant scheduling",
      "Routing complexity across teams",
      "Speed-to-lead is core value prop",
    ],
  },
  {
    id: "paddle",
    name: "Paddle",
    url: "https://www.paddle.com",
    description: "Billing and payments infrastructure for SaaS.",
    industry: "Billing",
    employeeCount: 420,
    fundingStage: "Series D+",
    fundingAmount: "$300M total",
    arrEstimate: "$100M-$200M",
    headquarters: "London, UK",
    region: "EMEA",
    products: ["Payments", "Tax compliance", "Subscription management"],
    demoPageUrl: "https://www.paddle.com/demo",
    techStack: ["AWS", "Salesforce", "Marketo", "Segment", "Snowflake"],
    buyerPersonas: ["CFO", "VP Finance", "RevOps"],
    hiringSignals: ["Hiring SDRs", "Hiring enterprise AEs", "Scaling RevOps"],
    painSignals: [
      "Multiple geographies require complex routing",
      "High-intent inbound from paid acquisition",
      "Enterprise demos require fast follow-up",
    ],
  },
  {
    id: "personio",
    name: "Personio",
    url: "https://www.personio.com",
    description: "HR software for mid-sized European companies.",
    industry: "HRIS",
    employeeCount: 450,
    fundingStage: "Series D+",
    fundingAmount: "$700M total",
    arrEstimate: "$200M-$400M",
    headquarters: "Munich, Germany",
    region: "EMEA",
    products: ["HRIS", "Recruiting", "Payroll", "Performance"],
    demoPageUrl: "https://www.personio.com/demo",
    techStack: ["AWS", "Salesforce", "HubSpot", "Segment", "Snowflake"],
    buyerPersonas: ["VP People", "HR Director", "COO"],
    hiringSignals: ["Hiring SDRs", "Hiring enterprise AEs", "Scaling RevOps"],
    painSignals: [
      "Routing by country and company size",
      "High demo dependency for enterprise",
      "Speed-to-lead impacts competitive wins",
    ],
  },
  {
    id: "freshworks",
    name: "Freshworks",
    url: "https://www.freshworks.com",
    description: "Customer engagement and CRM suite for global teams.",
    industry: "CRM",
    employeeCount: 5000,
    fundingStage: "Series D+",
    fundingAmount: "$400M total",
    arrEstimate: "$500M+",
    headquarters: "Chennai, India",
    region: "APAC",
    products: ["CRM", "Helpdesk", "ITSM", "Marketing automation"],
    demoPageUrl: "https://www.freshworks.com/demo",
    techStack: ["AWS", "Salesforce", "Marketo", "Segment", "Snowflake"],
    buyerPersonas: ["VP Sales", "Head of Support", "CIO"],
    hiringSignals: ["Hiring SDRs", "Hiring enterprise AEs", "Scaling global RevOps"],
    painSignals: [
      "Global routing across regions and products",
      "High inbound from paid and partner channels",
      "Complex lead qualification across teams",
    ],
  },
  {
    id: "darwinbox",
    name: "Darwinbox",
    url: "https://www.darwinbox.com",
    description: "Enterprise HR platform for global companies.",
    industry: "HRIS",
    employeeCount: 800,
    fundingStage: "Series D+",
    fundingAmount: "$200M total",
    arrEstimate: "$100M-$200M",
    headquarters: "Hyderabad, India",
    region: "APAC",
    products: ["Core HR", "Payroll", "Talent management", "Analytics"],
    demoPageUrl: "https://www.darwinbox.com/demo",
    techStack: ["AWS", "Salesforce", "HubSpot", "Segment", "PowerBI"],
    buyerPersonas: ["CHRO", "VP People", "HR Director"],
    hiringSignals: ["Hiring SDRs", "Hiring enterprise AEs", "Scaling RevOps"],
    painSignals: [
      "Complex routing by region and enterprise segment",
      "High demo dependency for enterprise deals",
      "Speed-to-lead critical in competitive HR market",
    ],
  },
  {
    id: "leapsome",
    name: "Leapsome",
    url: "https://www.leapsome.com",
    description: "People enablement for performance, engagement, and learning.",
    industry: "People Enablement",
    employeeCount: 180,
    fundingStage: "Series B",
    fundingAmount: "$60M total",
    arrEstimate: "$20M-$40M",
    headquarters: "Berlin, Germany",
    region: "EMEA",
    products: ["Performance reviews", "Engagement surveys", "Learning"],
    demoPageUrl: "https://www.leapsome.com/demo",
    techStack: ["AWS", "HubSpot", "Segment", "Salesforce", "Looker"],
    buyerPersonas: ["VP People", "HR Director", "COO"],
    hiringSignals: ["Hiring SDRs", "Hiring demand gen", "Scaling RevOps"],
    painSignals: [
      "Enterprise demos required for evaluation",
      "Routing by region and company size",
      "Response time affects conversion",
    ],
  },
  {
    id: "ashby",
    name: "Ashby",
    url: "https://www.ashbyhq.com",
    description: "All-in-one recruiting platform for scaling teams.",
    industry: "Recruiting",
    employeeCount: 230,
    fundingStage: "Series C",
    fundingAmount: "$100M total",
    arrEstimate: "$30M-$60M",
    headquarters: "San Francisco, CA",
    region: "NAM",
    products: ["ATS", "Scheduling", "Analytics", "Sourcing"],
    demoPageUrl: "https://www.ashbyhq.com/demo",
    techStack: ["AWS", "Salesforce", "HubSpot", "Segment", "Snowflake"],
    buyerPersonas: ["Head of Talent", "Recruiting Ops", "VP People"],
    hiringSignals: ["Hiring SDRs", "Hiring enterprise AEs", "Scaling RevOps"],
    painSignals: [
      "High demo dependency for enterprise hiring",
      "Routing by company size and vertical",
      "Fast response drives pipeline",
    ],
  },
  {
    id: "metronome",
    name: "Metronome",
    url: "https://www.metronome.com",
    description: "Usage-based billing infrastructure for SaaS.",
    industry: "Usage Billing",
    employeeCount: 180,
    fundingStage: "Series B",
    fundingAmount: "$75M total",
    arrEstimate: "$20M-$40M",
    headquarters: "San Francisco, CA",
    region: "NAM",
    products: ["Usage billing", "Metering", "Revenue analytics"],
    demoPageUrl: "https://www.metronome.com/demo",
    techStack: ["AWS", "Segment", "Salesforce", "Snowflake", "Looker"],
    buyerPersonas: ["VP Finance", "RevOps", "Head of Billing"],
    hiringSignals: ["Hiring SDRs", "Hiring solutions engineers", "Scaling enterprise sales"],
    painSignals: [
      "Complex routing by product line",
      "Enterprise demos require fast scheduling",
      "Speed-to-lead impacts conversion",
    ],
    isExistingCustomer: true,
  },
  {
    id: "kintsugi",
    name: "Kintsugi",
    url: "https://www.kintsugihealth.com",
    description: "AI platform for mental health support and care navigation.",
    industry: "Mental Health AI",
    employeeCount: 80,
    fundingStage: "Series A",
    fundingAmount: "$30M total",
    arrEstimate: "$5M-$12M",
    headquarters: "San Francisco, CA",
    region: "NAM",
    products: ["Care navigation", "AI screening", "Provider matching"],
    demoPageUrl: "https://www.kintsugihealth.com/demo",
    techStack: ["AWS", "HubSpot", "Segment", "Salesforce", "Looker"],
    buyerPersonas: ["VP Partnerships", "Healthcare Ops", "CIO"],
    hiringSignals: ["Hiring SDRs", "Hiring partnerships", "Scaling RevOps"],
    painSignals: [
      "Complex routing by provider network",
      "High-touch demos for healthcare buyers",
      "Speed-to-lead critical for partnerships",
    ],
    isExistingCustomer: true,
  },
  {
    id: "galley-solutions",
    name: "Galley Solutions",
    url: "https://www.galleysolutions.com",
    description: "Food service management platform for operations teams.",
    industry: "Food Service Operations",
    employeeCount: 90,
    fundingStage: "Series A",
    fundingAmount: "$25M total",
    arrEstimate: "$5M-$12M",
    headquarters: "New York, NY",
    region: "NAM",
    products: ["Menu management", "Recipe costing", "Inventory"],
    demoPageUrl: "https://www.galleysolutions.com/demo",
    techStack: ["AWS", "HubSpot", "Segment", "Salesforce", "Tableau"],
    buyerPersonas: ["VP Operations", "Culinary Director", "COO"],
    hiringSignals: ["Hiring SDRs", "Hiring operations", "Scaling RevOps"],
    painSignals: [
      "High-touch demos for operational buyers",
      "Routing by region and customer size",
      "Manual qualification slows pipeline",
    ],
    isExistingCustomer: true,
  },
  {
    id: "safetyculture",
    name: "SafetyCulture",
    url: "https://safetyculture.com",
    description: "Operations and safety management platform.",
    industry: "Operations",
    employeeCount: 1000,
    fundingStage: "Series D+",
    fundingAmount: "$300M total",
    arrEstimate: "$200M-$400M",
    headquarters: "Sydney, Australia",
    region: "APAC",
    products: ["Inspections", "Training", "Issues management"],
    demoPageUrl: "https://safetyculture.com/demo",
    techStack: ["AWS", "Salesforce", "Marketo", "Segment", "Looker"],
    buyerPersonas: ["VP Operations", "EHS Director", "COO"],
    hiringSignals: ["Hiring SDRs", "Hiring enterprise AEs", "Scaling RevOps"],
    painSignals: [
      "Complex routing by region and industry",
      "High demo dependency for enterprise",
      "Speed-to-lead impacts win rates",
    ],
  },
];

export const seedDataProvider: DataProvider = {
  getCompanies: () => companies,
  getCompanyById: (id: string) => companies.find((company) => company.id === id),
};
